title: Open Access Feminist Resources
theme: minima
collections:
  topics:
    output: true
  theories:
    output: true
  vocab:
    output: true
    order: 
    - patriarchy.md
    - misogyny.md
    - gender.md
    - sex.md
    - objectification.md
    - oppression.md
    - domestic_labor.md
  ideologies:
    output: true
  movements:
    output: true
  people:
    output: true

nav_pages:
    - index.html
    - about.html
    - basics.md
    - journals.md
    - PDFs.md
    - Videos.md

defaults:
  - scope:
      type: "topics"
    values:
      layout: tagged_item


defaults:
  - scope:
      type: "theories"
    values:
      layout: theory_item

defaults:
  - scope: 
      type: "ideologies"
    values:
      layout: ideology_item

defaults:
  - scope:
      type: "vocab"
    values:
      layout: vocab_item

defaults:
  -scope:
    type: "movements"
    values:
      layout: movement_item

defaults:
  -scope:
    type: "people"
    values:
      layout: person_item