title: Open Access Feminist Resources
baseurl: "/lis786-starterkit"
url: "https://haleyem.github.io"
theme: minima
collections:
  topics:
    output: true
  theories:
    output: true
    permalink: /theories/:title
  vocab:
    output: true
    permalink: /vocab/:title
    order: 
    - patriarchy.md
    - misogyny.md
    - gender.md
    - sex.md
    - objectification.md
    - oppression.md
    - domestic_labor.md
  ideologies:
    output: true
    permalink: /ideologies/:title
  movements:
    output: true
    permalink: /movements/:title
  people:
    output: true
    permalink: /people/:title


defaults:
  - scope:
      type: "topics"
    values:
      layout: tagged_item

defaults:
  - scope:
      type: "theories"
    values:
      layout: theory_item

defaults:
  - scope: 
      type: "ideologies"
    values:
      layout: ideology_item

defaults:
  - scope:
      type: "vocab"
    values:
      layout: vocab_item

defaults:
  -scope:
    type: "movements"
    values:
      layout: movement_item

defaults:
  -scope:
    type: "people"
    values:
      layout: person_item