title: Open Access Feminist Resources
theme: minima
collections:
  theories:
    output: true
  vocab:
    output: true
    order: 
    - patriarchy.md
    - misogyny.md
    - gender.md
    - sex.md
    - objectification.md
    - oppression.md
    - domestic_labor.md
nav_pages:
    - index.html
    - about.html
    - basics.md
    - journals.md
    - PDFs.md
    - Videos.md
defaults:
  - scope:
      type: "theories"
    values:
      layout: theory_item

defaults:
  - scope:
      type: "vocab"
    values:
      layout: vocab_item